// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Senseition.Datas;

namespace Senseition.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210319171643_TeacherCourseTable")]
    partial class TeacherCourseTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Senseition.Models.DataModels.Course", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("course_name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("id");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("Senseition.Models.DataModels.Faculty", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("faculty_name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("logo_url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Faculty");
                });

            modelBuilder.Entity("Senseition.Models.DataModels.Major", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("Facultyid")
                        .HasColumnType("bigint");

                    b.Property<long>("facult_id")
                        .HasColumnType("bigint");

                    b.Property<string>("major_logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("major_name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("id");

                    b.HasIndex("Facultyid");

                    b.ToTable("Major");
                });

            modelBuilder.Entity("Senseition.Models.DataModels.Survey", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("answer_question1")
                        .HasColumnType("tinyint");

                    b.Property<byte>("answer_question2")
                        .HasColumnType("tinyint");

                    b.Property<byte>("answer_question3")
                        .HasColumnType("tinyint");

                    b.Property<byte>("answer_question4")
                        .HasColumnType("tinyint");

                    b.Property<byte>("answer_question5")
                        .HasColumnType("tinyint");

                    b.HasKey("id");

                    b.ToTable("Survey");
                });

            modelBuilder.Entity("Senseition.Models.DataModels.Teacher", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("Majorid")
                        .HasColumnType("bigint");

                    b.Property<byte>("age")
                        .HasColumnType("tinyint");

                    b.Property<string>("biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("first_name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<long>("major_id")
                        .HasColumnType("bigint");

                    b.Property<string>("picture_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("position")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<byte>("rate")
                        .HasColumnType("tinyint");

                    b.HasKey("id");

                    b.HasIndex("Majorid");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("Senseition.Models.DataModels.TeacherCourse", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("Courseid")
                        .HasColumnType("bigint");

                    b.Property<long?>("Teacherid")
                        .HasColumnType("bigint");

                    b.Property<long>("course_id")
                        .HasColumnType("bigint");

                    b.Property<long>("teacher_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("Courseid");

                    b.HasIndex("Teacherid");

                    b.ToTable("TeacherCourse");
                });

            modelBuilder.Entity("Senseition.Models.DataModels.User", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("first_name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("user_picture_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usernam")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Senseition.Models.DataModels.Major", b =>
                {
                    b.HasOne("Senseition.Models.DataModels.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("Facultyid");
                });

            modelBuilder.Entity("Senseition.Models.DataModels.Teacher", b =>
                {
                    b.HasOne("Senseition.Models.DataModels.Major", "Major")
                        .WithMany()
                        .HasForeignKey("Majorid");
                });

            modelBuilder.Entity("Senseition.Models.DataModels.TeacherCourse", b =>
                {
                    b.HasOne("Senseition.Models.DataModels.Course", "Course")
                        .WithMany()
                        .HasForeignKey("Courseid");

                    b.HasOne("Senseition.Models.DataModels.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("Teacherid");
                });
#pragma warning restore 612, 618
        }
    }
}
